name: Moodle Plugin CI

########################################################################################################################
# Runs the Moodle Plugin CI workflow.
#
# Additional plugins may be required for this workflow to run, configurable with the inputs of this workflow
# the used branch included. If no branch is specified for a required plugin, the current branch is used.
########################################################################################################################

on:
  workflow_call:
    inputs:
      requires-tool-plugin:
        description: 'Specifies, whether the Opencast Tool plugin is required.'
        default: false
        required: false
        type: boolean
      branch-tool-plugin:
        description: 'Specifies the branch of the Opencast Tool plugin.'
        default: ""
        required: false
        type: string
      requires-mod-plugin:
        description: 'Specifies, whether the Opencast Activity plugin is required.'
        default: false
        required: false
        type: boolean
      branch-mod-plugin:
        description: 'Specifies the branch of the Opencast Activity plugin.'
        default: ""
        required: false
        type: string

########################################################################################################################

env:
  workflow_branch_name: ${{ github.head_ref || github.ref_name }}
  branch_tool_plugin: ${{ inputs.branch-tool-plugin || (github.head_ref || github.ref_name) }}
  branch_mod_plugin: ${{ inputs.branch-mod-plugin || (github.head_ref || github.ref_name) }}

########################################################################################################################

jobs:
  static:
    runs-on: ubuntu-latest
    name: static

    strategy:
      matrix:
        php: ['8.1']
        moodle-branch: ['MOODLE_401_STABLE']
        database: ['mariadb']

    steps:
      - name: Start MariaDB
        run: docker run -p 3306:3306 -e MYSQL_USER=root -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d mariadb:10

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(cd /home/runner/.composer && composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install tool plugin
        if: ${{ inputs.requires-tool-plugin == true }}
        run: moodle-plugin-ci add-plugin --branch master Opencast-Moodle/moodle-tool_opencast

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1 --no-init
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        continue-on-error: true
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker

      - name: Moodle PHPDoc Checker
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        if: ${{ always() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 1 # Dumb, but it seems like one warning is always generated
                                                          # because we have a third party file, which is ignored by default.

  ######################################################################################################################

  test:
    runs-on: ubuntu-latest
    needs: static
    name: test (${{matrix.moodle-branch}}/${{matrix.php}}/${{matrix.database}})

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']
        moodle-branch: ['MOODLE_39_STABLE', 'MOODLE_310_STABLE', 'MOODLE_311_STABLE', 'MOODLE_400_STABLE', 'MOODLE_401_STABLE']
        database: ['mariadb', 'pgsql']
        opencast: ['13.5']
        exclude:
          - moodle-branch: 'MOODLE_39_STABLE'
            php: '8.0'
          - moodle-branch: 'MOODLE_39_STABLE'
            php: '8.1'
          - moodle-branch: 'MOODLE_310_STABLE'
            php: '8.0'
          - moodle-branch: 'MOODLE_310_STABLE'
            php: '8.1'
          - moodle-branch: 'MOODLE_311_STABLE'
            php: '8.1'
          - moodle-branch: 'MOODLE_400_STABLE'
            php: '8.1'

    steps:
      - name: Start MariaDB
        if: matrix.database == 'mariadb'
        run: docker run -p 3306:3306 -e MYSQL_USER=root -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d mariadb:10

      - name: Start PostgreSQL
        if: matrix.database == 'pgsql'
        run: docker run -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_HOST_AUTH_METHOD=trust -d postgres:14

      - name: Check out opencast-docker
        uses: actions/checkout@v3
        with:
          repository: opencast/opencast-docker
          ref: ${{ matrix.opencast }}
          path: opencast-docker

      - name: Start Opencast
        run: docker-compose -p opencast-allinone -f opencast-docker/docker-compose/docker-compose.allinone.h2.yml up -d

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(cd /home/runner/.composer && composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install tool plugin
        if: ${{ inputs.requires-tool-plugin == true }}
        run: moodle-plugin-ci add-plugin --branch "${branch_tool_plugin}" Opencast-Moodle/moodle-tool_opencast

      - name: Install activity plugin
        if: ${{ inputs.requires-mod-plugin == true }}
        run: moodle-plugin-ci add-plugin --branch "${branch_mod_plugin}" Opencast-Moodle/moodle-mod_opencast

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHPUnit tests
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit

      - name: Behat features
        if: ${{ always() }}
        run: moodle-plugin-ci behat --auto-rerun 0
